kubens prototype
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>

diff --git a/kubectx b/kubectx
--- a/kubectx
+++ b/kubectx
@@ -21,6 +21,9 @@
 set -eou pipefail
 IFS=$'\n\t'
 
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+source "${SCRIPT_DIR}/utils.bash"
+
 KUBECTX="${HOME}/.kube/kubectx"
 
 usage() {
@@ -33,10 +36,6 @@ USAGE:
   kubectx -h,--help         : show this message
 EOF
   exit 1
-}
-
-current_context() {
-  kubectl config view -o=jsonpath='{.current-context}'
 }
 
 get_contexts() {
@@ -139,7 +138,8 @@ main() {
     elif [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
       usage
     elif [[ "${1}" =~ ^-(.*) ]]; then
-      echo "error: unrecognized flag" >&2; usage
+      echo "error: unrecognized flag \"${1}\"" >&2
+      usage
     elif [[ "${1}" =~ (.+)=(.+) ]]; then
       alias_context "${BASH_REMATCH[2]}" "${BASH_REMATCH[1]}"
     else
diff --git a/kubens b/kubens
--- a/kubens
+++ b/kubens
@@ -21,36 +21,56 @@
 set -eou pipefail
 IFS=$'\n\t'
 
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+source "${SCRIPT_DIR}/utils.bash"
+
 KUBENS_DIR="${HOME}/.kube/kubens"
 
 usage() {
   cat <<"EOF"
 USAGE:
   kubens                    : list the namespaces in the current context
-  kubens  <NAME>            : change the default namespace for current context
-  kubens -                  : switch to the previous namespace
+  kubens <NAME>             : change the active namespace of current context
+  kubens -                  : switch to the previous namespace in this context
   kubens -h,--help          : show this message
 EOF
   exit 1
 }
 
-current_context() {
-  kubectl config view -o=jsonpath='{.current-context}'
+get_namespaces() {
+  kubectl get namespaces -o=jsonpath='{range .items[*].metadata.name}{@}{"\n"}{end}'
 }
 
-get_contexts() {
-  kubectl config view \
-    -o=jsonpath='{range .contexts[*].name}{@}{"\n"}{end}'
+current_namespace() {
+  local cur_ctx=$(current_context)
+  ns="$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"${cur_ctx}\")].context.namespace}")"
+  if [[ -z "${ns}" ]]; then
+    echo "default"
+  else
+    echo "${ns}"
+  fi
 }
 
-list_contexts() {
-  set -u pipefail
-  local cur="$(current_context)"
+set_namespace() {
+  kubectl config set-context "$(kubectl config current-context)" --namespace="${1}"
+  echo "Active namespace is \"${1}\"."
+}
+
+switch_namespace() {
+  if grep -q ^"${1}"\$ <(get_namespaces); then
+    set_namespace "${1}" 
+  else
+    echo "Namespace \"${1}\" does not exist."
+  fi
+}
+
+list_namespaces() {
+  local cur="$(current_namespace)"
   local yellow=$(tput setaf 3)
   local darkbg=$(tput setab 0)
   local normal=$(tput sgr0)
 
-  for c in $(get_contexts); do
+  for c in $(get_namespaces); do
   if [[ "${c}" = "${cur}" ]]; then
     echo "${darkbg}${yellow}${c}${normal}"
   else
@@ -59,92 +79,24 @@ list_contexts() {
   done
 }
 
-read_context() {
-  if [[ -f "${KUBECTX}" ]]; then
-    cat "${KUBECTX}"
-  fi
-}
-
-save_context() {
-  local saved="$(read_context)"
-
-  if [[ "${saved}" != "${1}" ]]; then
-    printf %s "${1}" > "${KUBECTX}"
-  fi
-}
-
-switch_context() {
-  kubectl config use-context "${1}"
-}
-
-set_context() {
-  local prev="$(current_context)"
-
-  switch_context "${1}"
-
-  if [[ "${prev}" != "${1}" ]]; then
-    save_context "${prev}"
-  fi
-}
-
-swap_context() {
-  set -e
-  local ctx="$(read_context)"
-  if [[ -z "${ctx}" ]]; then
-    echo "error: No previous context found." >&2
-    exit 1
-  fi
-  set_context "${ctx}"
-}
-
-user_of_context() {
-  kubectl config view \
-    -o=jsonpath="{.contexts[?(@.name==\"${1}\")].context.user}"
-}
-
-cluster_of_context() {
-  kubectl config view \
-    -o=jsonpath="{.contexts[?(@.name==\"${1}\")].context.cluster}"
-}
-
-alias_context() {
-  local old_name="${1}"
-  local new_name="${2}"
-
-  local old_user="$(user_of_context "${old_name}")"
-  local old_cluster="$(cluster_of_context "${old_name}")"
-
-  if [[ -z "$old_user" || -z "$old_cluster" ]]; then
-    echo "error: Cannot retrieve context ${old_name}."  >&2
-    exit 1
-  fi
-
-  kubectl config set-context "${new_name}" \
-    --cluster="${old_cluster}" \
-    --user="${old_user}" \
-
-  echo "Aliased \"${old_name}\" as \"${new_name}\"." >&2
-}
-
 main() {
   if [[ "$#" -eq 0 ]]; then
-    list_contexts
-  elif [[ "$#" -gt 1 ]]; then
-    echo "error: too many flags" >&2
-    usage
+    list_namespaces
   elif [[ "$#" -eq 1 ]]; then
-    if [[ "${1}" == "-" ]]; then
-      swap_context
-    elif [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
+    if [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
       usage
+    elif [[ "${1}" == "-" ]]; then
+      swap_namespace
     elif [[ "${1}" =~ ^-(.*) ]]; then
-      echo "error: unrecognized flag" >&2; usage
+      echo "error: unrecognized flag \"${1}\"" >&2
+      usage
     elif [[ "${1}" =~ (.+)=(.+) ]]; then
       alias_context "${BASH_REMATCH[2]}" "${BASH_REMATCH[1]}"
     else
-      set_context "${1}"
+      switch_namespace "${1}"
     fi
   else
+    echo "error: too many flags" >&2
     usage
   fi
 }
